"""Training batch — 10 gold-standard conversations (yardstick, not fixed spec).

scope: "in"  -> graded semantically (discovery + reveal/shortlist, the bot's purpose)
       "out" -> skipped (scheduling a physical visit — agreed out of scope)
"""

def _c(customer, agent, scope="in", reason=""):
    return {"customer": customer, "expected_agent": agent, "scope": scope, "reason": reason}

SCHED = "scheduling / physical visit"

CONVERSATIONS = [
    {
        "name": "1. Low-budget first home — practical areas",
        "user_id": "batch01",
        "turns": [
            _c("Assalam o Alaikum. I'm looking for a flat in Karachi. Budget is around 1.4 to 1.5 crore.",
               "Wa Alaikum Assalam. Is this for your own living or investment?"),
            _c("Own living. We're a small family, husband, wife, and one child.",
               "Got it. How many bedrooms do you need?"),
            _c("Preferably 2 bed. I don't want a very small 1-bed.",
               "In this budget, areas like North Karachi, New Karachi, Landhi, Korangi, FB Area pockets, or some outer Scheme 33 options may work. Any area preference?"),
            _c("North Karachi, FB Area, or New Karachi are okay. Landhi/Korangi feel a bit far.",
               "Fair. Any must-haves?"),
            _c("Family building, lift if possible, clean entrance, water, and no major parking issue.",
               "Perfect. So I'll focus on 2-bed family flats around 1.5 crore in North Karachi, New Karachi, and selective FB Area options."),
            _c("Yes, that sounds right.",
               "Great, I'll shortlist only the relevant options now and avoid showing random flats."),
            _c("Okay. If there are 2-3 good ones, I can visit this weekend.",
               "Done. Let's plan Sunday afternoon after I confirm the strongest matches.", "out", SCHED),
        ],
    },
    {
        "name": "2. Premium buyer — DHA / Clifton lifestyle",
        "user_id": "batch02",
        "turns": [
            _c("Hi. I'm looking for a premium apartment in Karachi for my family.",
               "Sure. Are you looking around DHA, Clifton, or open to other premium areas too?"),
            _c("DHA and Clifton mainly. Maybe Bath Island if the building is excellent.",
               "Good. What budget range should I consider?"),
            _c("Around 8 to 10 crore.",
               "Understood. Bedrooms?"),
            _c("Minimum 3 bedrooms. Prefer 4 if possible. It should feel spacious.",
               "Any must-have amenities?"),
            _c("Dedicated parking, lift, standby generator, security, clean lobby, preferably gym or play area. Sea view is a plus, not compulsory.",
               "For this budget, I'll focus on well-managed buildings, not just fancy interiors. DHA Phase 5/6/8, Clifton blocks with better access, and Bath Island can be considered."),
            _c("Yes. I don't want an old building with maintenance problems.",
               "Perfect. So we'll prioritize premium 3-4 bed apartments, strong building management, parking, security, and family environment."),
            _c("Exactly.",
               "Great, I'll shortlist a few premium options and then we can physically inspect the building quality."),
            _c("Saturday evening works.",
               "Done. We'll start with DHA and keep Clifton as the second route.", "out", SCHED),
        ],
    },
    {
        "name": "3. Working couple — commute and security focused",
        "user_id": "batch03",
        "turns": [
            _c("I need a flat in Karachi. My office is near Shahrah-e-Faisal.",
               "Sure. Is this for family living?"),
            _c("Yes, me and my wife. Maybe kids in future.",
               "What budget range?"),
            _c("Around 2.5 to 3 crore.",
               "Then PECHS, Bahadurabad, SMCHS, Gulshan, KDA, and some parts of Johar can work. Do you want shorter commute or better apartment size?"),
            _c("Shorter commute is more important. Also security matters.",
               "Noted. Bedrooms?"),
            _c("2 bed is okay, but 3 bed would be better if available.",
               "Any must-haves?"),
            _c("Parking, lift, generator backup, decent building, and not a noisy street.",
               "So I'll prioritize secure, well-managed 2-3 bed apartments near Shahrah-e-Faisal access, especially PECHS, Bahadurabad, and nearby areas."),
            _c("Yes, don't show far areas just because they are bigger.",
               "Understood. I'll shortlist based on commute first, then building quality."),
            _c("Good. I can visit after office hours.",
               "Great. Let's plan Thursday around 7 pm.", "out", SCHED),
        ],
    },
    {
        "name": "4. Elderly parents — lift and hospital access",
        "user_id": "batch04",
        "turns": [
            _c("I'm looking for a flat for my parents in Karachi.",
               "Sure. Their comfort will be the main priority. What budget?"),
            _c("Around 1.8 to 2.2 crore.",
               "How many bedrooms?"),
            _c("2 bedrooms are enough.",
               "Any specific areas?"),
            _c("North Nazimabad, Gulshan, or FB Area. Somewhere peaceful and accessible.",
               "For parents, I'd avoid buildings with stairs, poor lift maintenance, or difficult parking. Is lift compulsory?"),
            _c("Yes, lift is compulsory. Also nearby hospital, mosque, and market would be good.",
               "Noted. Lower or middle floor preferred?"),
            _c("Lower floor if possible, but only if the building has lift.",
               "Perfect. I'll look for 2-bed flats in accessible areas with lift, easy entrance, stable utilities, and nearby daily facilities."),
            _c("Yes. Please don't show congested buildings.",
               "Understood. I'll shortlist only parent-friendly options."),
            _c("I can visit with my father on Sunday morning.",
               "Done. Sunday morning is good because we can also check the building's daily environment.", "out", SCHED),
        ],
    },
    {
        "name": "5. Joint family — independent house preferred",
        "user_id": "batch05",
        "turns": [
            _c("We need a house in Karachi for a joint family.",
               "Sure. How many family members and what budget?"),
            _c("Around 8 people. Budget is 5 to 6 crore.",
               "Do you want an independent house only, or would a large portion also work?"),
            _c("Independent house preferred. Portion only if it feels private.",
               "How many bedrooms do you need?"),
            _c("At least 4 bedrooms, ideally 5.",
               "Which areas are suitable?"),
            _c("Gulshan, North Nazimabad, FB Area, or maybe Scheme 33 if the society is good.",
               "Any must-haves?"),
            _c("Two car parking, separate drawing room, decent street, and no water issue.",
               "For a joint family, layout matters a lot. I'll avoid houses that only look big but have awkward room distribution."),
            _c("Exactly. We need practical space.",
               "So I'll shortlist 4-5 bed houses or very private portions in Gulshan, North Nazimabad, FB Area, and strong Scheme 33 societies."),
            _c("Good. We can visit on Saturday.",
               "Done. I'll arrange a route with the least travel time between options.", "out", SCHED),
        ],
    },
    {
        "name": "6. Unrealistic expectation — DHA budget mismatch",
        "user_id": "batch06",
        "turns": [
            _c("I want a 3-bed flat in DHA or Clifton. Budget is 2 crore.",
               "Understood. Is DHA/Clifton compulsory, or are you open to nearby alternatives?"),
            _c("I prefer DHA or Clifton only.",
               "For a proper 3-bed family apartment, 2 crore will be very difficult in DHA/Clifton unless there is a major compromise in size, building age, or location."),
            _c("What kind of compromise?",
               "Possibly older building, smaller unit, no proper parking, or less ideal block. If you want a decent 3-bed, areas like PECHS, Gulshan, Johar, or Scheme 33 may give better value."),
            _c("I don't want a bad building. I can consider PECHS or Gulshan then.",
               "Good decision. What matters more: area name or quality of living?"),
            _c("Quality of living. Family building, lift, parking, and safe surroundings.",
               "Then I'll focus on 3-bed flats around 2 crore in Gulshan, Johar, PECHS pockets, and maybe Scheme 33."),
            _c("Yes, but keep commute reasonable.",
               "Done. I'll shortlist realistic options instead of forcing DHA/Clifton compromises."),
            _c("Okay. Let's visit the best 3 options this weekend.",
               "Sure. Saturday afternoon works well.", "out", SCHED),
        ],
    },
    {
        "name": "7. Amenities-first buyer — gated community",
        "user_id": "batch07",
        "turns": [
            _c("I want a flat in a proper project with amenities.",
               "Sure. What kind of amenities are must-have?"),
            _c("Security, kids play area, mosque, parking, standby generator, and clean maintenance.",
               "What budget range?"),
            _c("Around 2.3 to 2.8 crore.",
               "Bedrooms?"),
            _c("3 bedrooms preferred.",
               "Which areas are you considering?"),
            _c("Scheme 33, Bahria Town Karachi, Saadi Town, or any good gated-style project.",
               "Do you commute daily to central Karachi?"),
            _c("Yes, mostly Gulshan and sometimes Shahrah-e-Faisal.",
               "Then we should be careful. Bahria may offer amenities, but commute can be heavy. Scheme 33 or Saadi-side projects may balance amenities and access better."),
            _c("Yes, I don't want daily travel to become painful.",
               "Perfect. I'll shortlist 3-bed apartments in managed projects with amenities, but I'll also filter by practical commute."),
            _c("Good. I want to see the society environment too.",
               "Then we'll visit during evening when families are around and amenities are active.", "out", SCHED),
            _c("Sunday evening works.",
               "Done. I'll arrange the strongest options first.", "out", SCHED),
        ],
    },
    {
        "name": "8. Overseas buyer — ready possession and legal clarity",
        "user_id": "batch08",
        "turns": [
            _c("I'm currently abroad but planning to move back to Karachi.",
               "Sure. Are you looking for a ready-to-move property?"),
            _c("Yes, no files or under-construction projects. I want possession.",
               "Good. What budget?"),
            _c("Around 3.5 to 4 crore.",
               "Apartment or house?"),
            _c("Apartment preferred. 3 bedrooms.",
               "Any preferred areas?"),
            _c("Gulshan, PECHS, Clifton if possible, or North Nazimabad. Family-friendly area matters.",
               "For overseas buyers, I'll prioritize clear documentation, possession, utilities, building condition, and seller credibility."),
            _c("Exactly. I don't want legal headaches.",
               "Will someone in Karachi visit on your behalf?"),
            _c("Yes, my brother can visit.",
               "Perfect. I'll shortlist only ready-possession 3-bed apartments with clear details and avoid unclear or risky listings."),
            _c("Good. First send options, then my brother can physically check.",
               "Done. Let's schedule his visit for Saturday after I verify availability and documents.", "out", SCHED),
        ],
    },
    {
        "name": "9. School-driven family — area depends on children",
        "user_id": "batch09",
        "turns": [
            _c("I need a flat mainly because of my kids' school.",
               "Understood. Which school area do you need access to?"),
            _c("Gulshan/Johar side. I don't want a long school commute.",
               "Budget?"),
            _c("Around 2.7 to 3.2 crore.",
               "Bedrooms?"),
            _c("3 bedrooms. We are husband, wife, two kids, and my mother.",
               "Then lift, parking, and family environment are important?"),
            _c("Yes. Also backup for lift, because my mother cannot take stairs.",
               "Any areas you want to avoid?"),
            _c("Very congested streets and buildings without proper maintenance.",
               "Makes sense. I'll focus on Gulshan and Johar first, especially locations with easier school routes, then maybe Scheme 33 only if access is good."),
            _c("Yes. Bigger flat is nice, but school commute is more important.",
               "Perfect. I'll shortlist 3-bed family flats based on school access, lift, parking, and building condition."),
            _c("Good. My wife and I can visit Friday after school time.",
               "Done. Friday afternoon is ideal to judge traffic as well.", "out", SCHED),
        ],
    },
    {
        "name": "10. Cautious buyer — bad past experience",
        "user_id": "batch10",
        "turns": [
            _c("I want to buy a flat, but I had a bad experience before with unclear documents.",
               "I understand. This time we'll be strict with documentation. What budget?"),
            _c("Around 2 crore.",
               "Bedrooms?"),
            _c("2 or 3 bedrooms. 3 would be better, but only if the building is reliable.",
               "Which areas?"),
            _c("Gulshan, Scheme 33, Gulistan-e-Johar, or North Nazimabad.",
               "Do you want ready possession only?"),
            _c("Yes. No booking, no file, no \"future possession\".",
               "Good. I'll only consider ready properties with clear ownership, utility status, and proper transfer process."),
            _c("Also, I don't want illegal floors or buildings with disputes.",
               "Noted. I'll avoid risky listings even if the price looks attractive."),
            _c("Perfect. I prefer safe over cheap.",
               "Then I'll shortlist legally cleaner, ready-possession 2-3 bed flats around 2 crore in your preferred areas."),
            _c("Good. I can visit with a family member and later bring a lawyer if needed.",
               "That's sensible. Let's visit the shortlisted options on Saturday, then proceed only with verified documents.", "out", SCHED),
        ],
    },
]
